exports.PARAM_INVALID = 100;
exports.PARAM_EMAIL_INVALID = 101;
exports.PARAM_ACCOUNT_INVALID = 104;
exports.PARAM_EMAIL_NOT_EXIST = 102;
exports.PARAM_PASSWORD_INVAILD = 103;
exports.SHARE_CAN_NOT_GEN_CODE = 105;
exports.SHARE_BODY_INVALID = 106;
exports.SHARE_MYSELF = 107;
exports.SHARE_ACCOUNT_NOT_EXIST = 108;
exports.SHARE_CODE_INVAILD = 109;
exports.SHARE_SET_PERMISSION_ERROR = 110;
exports.SHARE_CAN_NOT_REMOVE_YOUR_ACCOUNT = 111;
exports.SHARE_EMAIL_ALREADY_SHARED = 112;

exports.USER_NOT_EXIST = 901;
exports.USER_HAVE_NOT_PERMISSION = 902;
exports.USER_UNAUTHORITE = 903;
exports.USER_DEACTIVATED = 904;
exports.USER_EXPIRED = 905;
exports.SUBSCRIPTION_INFO_WRONG = 906;
exports.SUBSCRIPTION_PRODUCT_ERROR = 907;
exports.SOCIAL_ID_AND_EMAIL_REGISTERED = 908;
exports.SOCIAL_ID_REGISTERED_WITH_ANOTHER_EMAIL = 909;
exports.SOCIAL_EMAIL_REGISTERED_WITHOUT_SOCIAL_ID = 910;
exports.SOCIAL_EMAIL_REGISTERED_WITH_ANOTHER_SOCIAL_ID = 911;
exports.PHONE_NUMBER_INVALID = 912;
exports.PHONE_NUMBER_ALREADY_USED = 913;
exports.PHONE_NUMBER_WRONG_CONFIRMATION_CODE = 914;

exports.ACCOUNT_HAS_BEEN_ADDED = 801;

// sync errors
exports.SYNC_DATA_INVAILD_FORMAT = 701;
exports.SYNC_ACCOUNT_CAN_NOT_READ = 702;
exports.SYNC_ACCOUNT_CAN_NOT_WRITE = 703;
exports.SYNC_ERROR_INFO = 704;
exports.OAUTH_EXPIRE = 706;
exports.SYNC_DUPLICATE_ITEM = 707;
exports.SYNC_DATETIME_ERROR = 708;
exports.SYNC_NO_RECORD_ON_DB = 709;
exports.SYNC_UNKNOWN_ERROR = 799;

exports.DATABASE_ERROR = 601;
exports.UPLOAD_ERROR = 602;

exports.ACCOUNT_NOT_FOUND = 501;
//exports.TRANSACTION_NOT_FOUND = 502;

exports.OVER_DATA_QUOTA = 401;
exports.SYNC_SERVER_MAINTAINCE = 404;
exports.SYNC_ERROR_TYPE_DATA = 701;
exports.APP_OUT_OF_DATE = 406;
exports.REMOTE_WALLET_NOT_FOUND = 408;

exports.USER_ERROR_EMAIL_EXISTS = 200;
exports.USER_ERROR_SERIALS = 201;
exports.USER_ERROR_EMPTY_SERIALS = 208;
exports.USER_WARNING_INFO = 202;
exports.USER_ERROR_EVENT_EXPIRE = 203;
exports.ERROR_SERVER = 204;
exports.USER_ERROR_EMAIL_OR_PASSWORD = 205;
exports.USER_ERROR_NOT_EMAIL = 206;
exports.USER_ERROR_EMAIL_NOT_EXIST = 207;
exports.ACTIVE_ERROR_MISSING_INFO = 209;
exports.OAUTH_ERROR_CLIENT_SECRET_NOT_VALIDATE = 210;
exports.LIMIT_DEVICE = 212;
exports.USER_NOT_LOGIN = 213;
exports.INVITE_ERROR_DATA = 214;
exports.CAN_NOT_CHANGE_DEVICE = 215;
exports.SOCIAL_ID_NOT_FOUND = 216;
exports.USER_LOGGED_IN = 217;
exports.OUT_OF_USE_CREDIT = 218;
exports.RECEIPT_IMAGE_EXISTS = 219;
exports.ITEM_NOT_REGISTER = 220;
exports.ITEM_ALREADY_PURCHASED = 221;
exports.ITEM_BILL_INVALID = 222;
exports.ITEM_BILL_DUPLICATE = 223;
exports.USER_TAG_INVALID = 224;
exports.ITEM_PLATFORM_NOT_MATCH = 225;
exports.USER_TAG_DUPLICATED = 226;

exports.FILE_NOT_ALLOW = 300;
exports.FILE_SAVE_ERROR = 301;
exports.FILE_SIZE_OVER = 302;
exports.FILE_CAN_NOT_READ = 303;
exports.FILE_SYNC_INTERNAL_ERROR = 304;


exports.CODE_NOT_FOUND = 1001;
exports.SUBSCRIPTION_CODE_EXPIRE = 1004;
exports.SUBSCRIPTION_CANCEL = 1005;
exports.USER_DUPLICATE_PREMIUM = 1006;
exports.REF_INVAILD = 1008;
/****FINSIFY HERE****/
exports.FINSIFY_LOGIN_INVALID = 802;
exports.FINSIFY_ID_EXISTS = 803;
exports.FINSIFY_SERVICE_NOT_FOUND = 804;

exports.FINSIFY_TOKEN_NOT_FOUND = 806;
exports.FINSIFY_LOGIN_NOT_FOUND = 807;
exports.FINSIFY_ACCOUNT_NOT_FOUND = 808;
exports.FINSIFY_CUSTOMER_EXISTS = 809;
exports.FINSIFY_DATA_INVALID = 810;
exports.FINSIFY_SERVER_MAINTENANCE = 888;
exports.FINSIFY_SERVER_ERROR = 818;

exports.FINSIFY_MONEYLOVE_RREMOTEWALLET_NOTFOUND = 820;
exports.FINSIFY_WRONG_CREDENTIALS = 821;
exports.FINSIFY_PASSWORD_EXPIRED = 822;
exports.FINSIFY_ACCOUNT_LOCKED = 823;
